Repository AY2021S2-CS2113T-W09-3/tp, pull requests merged in 2021-03, with the labels that each got.

#23 Fix failing CI
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/module/ModuleList.java
  src/main/java/seedu/duke/storage/Loader.java
  src/main/java/seedu/duke/storage/Writer.java
  src/test/java/seedu/duke/commands/AddTaskTest.java
  src/test/java/seedu/duke/commands/CommandTestUtil.java
  src/test/java/seedu/duke/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/duke/commands/ListTasksCommandTest.java
  src/test/java/seedu/duke/commands/MarkAsDoneCommandTest.java
  src/test/java/seedu/duke/commands/MarkAsUndoneCommandTest.java
  src/test/java/seedu/duke/module/ModuleListStorageTest.java
  src/test/java/seedu/duke/storage/WriterTest.java
  src/test/java/seedu/duke/storage/reference/all_content_reference.txt
  src/test/java/seedu/duke/storage/reference/empty_reference.txt
  src/test/java/seedu/duke/storage/reference/invalid_content_reference.txt
  src/test/java/seedu/duke/storage/reference/invalid_file_reference.txt
  src/test/java/seedu/duke/storage/reference/lesson_only_reference.txt
  src/test/java/seedu/duke/storage/reference/task_only_reference.txt
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug

#115 Help command temp fix
  src/main/java/seedu/duke/commands/PrintHelpCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/commands/PrintHelpCommandTest.java
Labels: priority.High, type.Bug

#113 Sort lessons by type
  src/main/java/seedu/duke/commands/ListLessonsCommand.java
  src/main/java/seedu/duke/commands/SortLessonsCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/test/java/seedu/duke/commands/AddLessonCommandTest.java
  src/test/java/seedu/duke/commands/SortLessonsCommandTest.java
  src/test/java/seedu/duke/commands/ViewTeachingStaffCommandTest.java
Labels: priority.High

#150 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#157 Add proper tests to Parser and EditLessonCommand
  src/main/java/seedu/duke/commands/EditLessonCommand.java
  src/main/java/seedu/duke/module/ModuleList.java
  src/test/java/seedu/duke/commands/EditLessonCommandTest.java
  src/test/java/seedu/duke/commands/ExitModuleCommandTest.java
  src/test/java/seedu/duke/commands/LessonCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: priority.High, type.Enhancement

#174 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#179 General code cleanup 5
  src/main/java/seedu/duke/commands/DeleteLessonCommand.java
  src/main/java/seedu/duke/commands/EditLessonCommand.java
  src/main/java/seedu/duke/commands/ListTasksCommand.java
  src/main/java/seedu/duke/commands/ModuleInfoCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/module/Module.java
  src/main/java/seedu/duke/ui/UI.java
Labels: type.Task

#199 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/developerGuideImages/command-component-level.png
  docs/developerGuideImages/main-loop-sequence-diagram.png
Labels: type.Task

#208 Update README.md and AboutUs.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/developerGuideImages/addCheatSheetCommand-part1.png
  docs/developerGuideImages/addCheatSheetCommand-part2.png
  docs/developerGuideImages/addCheatSheetCommand.png
Labels: type.Task
